# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ColemanJustin_FinalProject' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ColemanJustin_FinalProject

pod 'Firebase/Core'
pod 'Firebase/Auth'
pod ’Firebase/Firestore'
pod 'Firebase/Storage'
pod 'MaterialComponents'
pod 'Validator'
pod 'ImageButter'
pod 'WordPress-iOS-Editor'
pod 'DateToolsSwift'
pod 'Fusuma'
pod 'FBSDKLoginKit'

end
